
"""
GolfAI Config
Version: v0.1
"""

DATA_FOLDER = "/kaggle/input/datasets/daveg1234/golf-ai-data"
DEFAULT_CLUB_FILTER = "7"
DISPERSION_CORRIDOR_M = 5.0

SMASH_GOOD = 1.30
SMASH_BAD = 1.18
SMASH_STD_GOOD = 0.03
SMASH_STD_BAD = 0.10

LAUNCH_BIAS_GOOD = 0.5
LAUNCH_BIAS_BAD = 4.0
LAUNCH_STD_GOOD = 1.0
LAUNCH_STD_BAD = 4.5

CARRY_STD_GOOD = 5.0
CARRY_STD_BAD = 20.0
